//
/***********************************************************************/
/*                                                                     */
/*  FILE        :init.c                                               */
/*  DATE        :Thu, Apr 19, 2012                                     */
/*  DESCRIPTION :serial comunication file.                             */
/*  CPU GROUP   :15                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.13).    */
/*                                                                     */
/***********************************************************************/
#include "sfr_r823.h" 											// R8C/23 SFR定義ファイル
#include "StackBlock.h"

void init_PORT(void);
void init_AD(void);

void init_PORT(void){
	prc2=1;
	pd0_0=1;
	prc2=1;
	pd0_1=1;
	prc2=1;
	pd0_2=1;
	prc2=1;
	pd0_3=1;
	prc2=1;
	pd0_4=1;
	prc2=1;
	pd0_5=1;
	prc2=1;
	pd0_6=1;
	prc2=1;
	pd0_7=1;
	prc2=1;
	pd1_0=1;
	pd1_1=1;
	pd1_2=1;
	pd1_3=0;
//	pd1_4=1;
//	p1_4=1;
	pd1_5=0;
	pd1_6=1;
	pd1_7=1;
	pd2_0=1;
	pd2_1=1;
	pd2_2=1;
	pd2_3=1;
	pd2_4=1;
	pd2_5=1;
	pd2_6=1;
	pd2_7=1;
	pd2_0=1;
	pd2_1=1;
	pd2_2=1;
	pd2_3=1;
	pd2_5=1;
	pd2_6=1;
	pd3_3=1;
	pd3_4=1;
	pd3_5=1;
	pd3_7=1;
	pd4_3=1;
	pd4_4=1;
	pd4_5=1;
	pd6_0=1;
	pd6_1=1;
	pd6_2=1;
	pd6_3=1;
	pd6_4=1;
	pd6_5=1;
	send_x(1,0b00000000);
	send_x(2,0b00000000);
	send_y(UP,0b00000000);
	p0_3=0;
	p0_7=0;
	p3_3=1;
	p6_0=1;
}

void init_AD()
{ //A/Nコンバータ入力モード
	ch0=1;
	ch1=1;
	ch2=1;
	adgsel0=1;
	adcap=0;
	cks0=1;
	cks1=0;
	bits=1;
	vcut=1;
	smp=1;
}